#include "legic_prime_listener_i.h"

#include "nfc/protocols/nfc_listener_base.h"
#include <furi_hal_nfc.h>
#include <nfc/helpers/legic_prime_crc.h>

#define TAG "LegicPrimeListener"

LegicPrimeListener *legic_prime_listener_alloc(Nfc *nfc, LegicPrimeData *data) {
  furi_assert(nfc);
  furi_assert(data);

  LegicPrimeListener *instance = malloc(sizeof(LegicPrimeListener));
  instance->nfc = nfc;
  instance->data = data;

  nfc_config(instance->nfc, NfcModeListener, NfcTechLegicPrime);

  nfc_legic_prime_listener_tx(nfc, (uint8_t *)data);
  return instance;
}

void legic_prime_listener_free(LegicPrimeListener *instance) {
  furi_assert(instance);

  free(instance);
}

void legic_prime_listener_set_callback(LegicPrimeListener *listener,
                                       NfcGenericCallback callback,
                                       void *context) {
  UNUSED(listener);
  UNUSED(callback);
  UNUSED(context);
}

const LegicPrimeData *
legic_prime_listener_get_data(const LegicPrimeListener *instance) {
  furi_assert(instance);
  furi_assert(instance->data);

  nfc_legic_prime_listener_rx(instance->nfc, (uint8_t *)instance->data);
  return instance->data;
}

NfcCommand legic_prime_listener_run(NfcGenericEvent event, void *context) {
  UNUSED(context);
  furi_assert(event.protocol == NfcProtocolInvalid);
  furi_assert(event.event_data);

  NfcEvent *nfc_event = event.event_data;
  NfcCommand command = NfcCommandContinue;

  // The user abort event is the only one this function will ever get, since all
  // others are generated by the nfc chip, which is running in transparent mode
  // and won't generate interrupts other than "FieldOn", whis is consumed by the
  // HAL.
  if (nfc_event->type == NfcEventTypeUserAbort) {
  }
  return command;
}

const NfcListenerBase nfc_listener_legic_prime = {
    .alloc = (NfcListenerAlloc)legic_prime_listener_alloc,
    .free = (NfcListenerFree)legic_prime_listener_free,
    .set_callback = (NfcListenerSetCallback)legic_prime_listener_set_callback,
    .get_data = (NfcListenerGetData)legic_prime_listener_get_data,
    .run = (NfcListenerRun)legic_prime_listener_run,
};
